apiVersion: v1
kind: Service
metadata:
  name: dhcp
  labels:
    run: dhcp
spec:
  type: ClusterIP
  ports:
  - port: 3300
    targetPort: 3300
    protocol: TCP
    name: dhcp
  selector:
    app: dhcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp
  labels:
    app: dhcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dhcp
  template:
    metadata:
      labels:
        app: dhcp
    spec:
      nodeSelector:
        location: main
      containers:
      - name: sidecar-debug
        image: debian:stretch
        command: ["/bin/sh", "-c"]
        args:
          - apt update; apt install isc-dhcp-client -y; sleep 999999
      - name: dhcp
        image: nsone/standalone_dhcp:5f4b88c4b
        imagePullPolicy: IfNotPresent
        env:
        - name: CONTAINER_NAME
          value: "dhcp"
        - name: CONFIG_PORT
          value: "3300"
        args:
        - "--pop_id=default_pop"
        - "--server_id=dhcp_server"
        - "--core_host=core"
        - "--enable_ops_metrics=false"
        livenessProbe:
          exec:
            command:
            - supd
            - health
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - mountPath: /ns1/data
          name: ns1-data
      volumes:
      - name: ns1-data
        emptyDir: {}
      imagePullSecrets:
      - name: docker-creds
