apiVersion: v1
kind: Service
metadata:
  name: xfr
  labels:
    run: xfr
spec:
  type: ClusterIP
  ports:
  - port: 3300
    targetPort: http-config
    protocol: TCP
    name: http-config
  - port: 9090
    targetPort: service
    protocol: TCP
    name: service
  - port: 53
    targetPort: xfr-udp
    protocol: UDP
    name: xfr-udp
  - port: 53
    targetPort: xfr-tcp
    protocol: TCP
    name: xfr-tcp
  selector:
    app: xfr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xfr
  labels:
    app: xfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xfr
  template:
    metadata:
      labels:
        app: xfr
    spec:
      nodeSelector:
        location: main
      containers:
      - name: xfr
        image: nsone/standalone_xfr:5f4b88c4b
        env:
        - name: CONTAINER_NAME
          value: "xfr"
        - name: CONFIG_PORT
          value: "3300"
        ports:
        - name: http-config
          containerPort: 3000
          protocol: TCP
        - name: service
          containerPort: 9090
          protocol: TCP
        - name: xfr-udp
          containerPort: 53
          protocol: UDP
        - name: xfr-tcp
          containerPort: 53
          protocol: TCP
        args:
        - "--pop_id=default_pop"
        - "--server_id=xfr_server"
        - "--core_host=core"
        - "--enable_ops_metrics=false"
        livenessProbe:
          exec:
            command:
            - supd
            - health
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - mountPath: /ns1/data
          name: ns1-data
      volumes:
      - name: ns1-data
        emptyDir: {}
      imagePullSecrets:
      - name: docker-creds
