---
version: '3.2'
services:
  core:
    image: ns1inc/privatedns_core:${TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3300 # are on the host machine
      CONTAINER_NAME: ${CORE_CONTAINER_NAME:-core}
      BOOTSTRAPPABLE: "true"
    restart: unless-stopped
    ports:
      - "5353:5353"      # data transport
      - "3300:3300"      # http configuration
      - "443:443"        # https connections to portal or api
      - "80:80"          # http connections to portal or api
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1core
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id             ${POP_ID:-mypop}
      --server_id          ${SERVER_ID:-myserver}
      --data_host          ${DATA_HOSTS:-data}
      --api_hostname       ${API_FQDN:-localhost}
      --portal_hostname    ${PORTAL_FQDN:-mycompany.net}
      --nameservers        ${NAMESERVERS:-mycompany.net}
      --hostmaster_email   ${HOSTMASTER_EMAIL:-admin@mycompany.net}
      --enable_ops_metrics true

  data:
    image: ns1inc/privatedns_data:${TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:          # keep environment lines if 2+ containers
      CONFIG_PORT: 3301   # are on the host machine
      CONTAINER_NAME: ${DATA_CONTAINER_NAME:-data}
      DATA_PRIMARY: "true"
    stop_grace_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "3301:3300" # http configuration
      - "8681:8686" # metrics export
      - "5352:5353" # replication
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0 # enable ipv6 for loopback
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1data
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id               ${POP_ID:-mypop}
      --server_id            ${SERVER_ID:-myserver}
      --enable_ops_metrics   true
      --expose_ops_metrics   true
      --cluster_mode         clustering_off

  dns:
    image: ns1inc/privatedns_dns:${TAG} 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3305 # are on the host machine
      CONTAINER_NAME: ${DNS_CONTAINER_NAME:-dns}
    restart: unless-stopped
    ports:
      - "3305:3300" # http configuration
      - "53:53/udp" # udp port for dns
      - "53:53/tcp" # tcp port for dns
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dns
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              ${POP_ID:-mypop}
      --server_id           ${SERVER_ID:-myserver}
      --core_host           ${DIST_OR_CORE_HOSTS:-core}
      --operation_mode      ${OPERATION_MODE:-authoritative}
      --enable_ops_metrics  true
      
  dnskey:
    image: ns1inc/privatedns_dnskey:${TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      CONFIG_PORT: 3309
      CONTAINER_NAME: ${PROBE_CONTAINER_NAME:-dnskey}
    restart: unless-stopped
    ports:
      - "3309:3300"      # http configuration
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dnskey
        target: /ns1/data
        volume:
          nocopy: true
      - "./keyring.yml:/ns1/data/etc/dnskeyd/keyring.yml:ro"
    command: >-
      --core_host       ${CORE_HOSTS:-core}
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.11.0/24
volumes:
  ns1data:
  ns1core:
  ns1dns:
  ns1dnskey:
