---
version: '3.2'
services:
  dns:
    image: ns1inc/privatedns_dns:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3301 # are on the host machine
      CONTAINER_NAME: ${DNS_CONTAINER_NAME:-dns}
    restart: unless-stopped
    ports:
      - "3301:3300" # http configuration
      - "9091:9090" # service proxy
      - "53:53/udp" # udp port for dns
      - "53:53/tcp" # tcp port for dns
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dns
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              ${POP_ID:-mypop}
      --server_id           ${SERVER_ID:-myserver}
      --core_host           ${DIST_OR_CORE_HOSTS:-dist}
      --operation_mode      ${OPERATION_MODE:-authoritative}
      --enable_ops_metrics  true
  dhcp:
    image: ns1inc/privatedns_dhcp:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3305 # are on the host machine
      CONTAINER_NAME: ${DHCP_CONTAINER_NAME:-dhcp}
    privileged: true
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dhcp
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              ${POP_ID:-mypop}
      --server_id           ${SERVER_ID:-myserver}
      --core_host           ${DIST_OR_CORE_HOSTS:-dist}
      --enable_ops_metrics  true
  dist:
    image: ns1inc/privatedns_dist:${TAG:-2.1.0}
    environment:
      CONFIG_PORT: 3304
      CONTAINER_NAME: ${DIST_CONTAINER_NAME:-dist}
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "3304:3300" # http configuration
      - "9094:9090" # service proxy
      - "5353"      # data transport
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0 # enable ipv6 for loopback
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dist
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id               ${POP_ID:-mypop}
      --server_id            ${SERVER_ID:-myserver}
      --core_host            ${CORE_HOSTS:-core}
      --enable_ops_metrics   true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.11.0/24
volumes:
  ns1dns:
  ns1dist:
  ns1dhcp:
