---
version: '3.2'
services:
  data:
    image: nsone/standalone_data:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3300 # are on the host machine
      CONTAINER_NAME: ${DATA_CONTAINER_NAME:-data}
      DATA_PRIMARY: "true"
    stop_grace_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "3300:3300" # http configuration
      - "9090:9090" # service proxy
      - "8686:8686" # metrics export
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0 # enable ipv6 for loopback
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1data
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id               ${POP_ID:-mypop}
      --server_id            ${SERVER_ID:-myserver}
      --enable_ops_metrics   true
      --expose_ops_metrics   true
  core:
    image: nsone/standalone_core:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3302 # are on the host machine
      CONTAINER_NAME: ${CORE_CONTAINER_NAME:-core}
    restart: unless-stopped
    ports:
      - "5353:5353" # data transport
      - "3302:3300"     # http configuration
      - "9092:9090"     # service proxy
      - "443:443"       # https connections to portal or api
      - "80:80"         # http connections to portal or api
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1core
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id             ${POP_ID:-mypop}
      --server_id          ${SERVER_ID:-myserver}
      --data_host          ${DATA_HOSTS:-data}
      --api_hostname       ${API_FQDN:-api.mycompany.net}
      --portal_hostname    ${PORTAL_FQDN:-portal.mycompany.net}
      --nameservers        ${NAMESERVERS:-ns1.mycompany.net}
      --hostmaster_email   ${HOSTMASTER_EMAIL:-hostmaster@mycompany.net}
      --enable_ops_metrics true
  dns:
    image: nsone/standalone_dns:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3301 # are on the host machine
      CONTAINER_NAME: ${DNS_CONTAINER_NAME:-dns}
    restart: unless-stopped
    ports:
      - "3301:3300" # http configuration
      - "9091:9090" # service proxy
      - "53:53/udp" # udp port for dns
      - "53:53/tcp"     # tcp port for dns
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dns
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              ${POP_ID:-mypop}
      --server_id           ${SERVER_ID:-myserver}
      --core_host           ${DIST_OR_CORE_HOSTS:-core}
      --operation_mode      ${OPERATION_MODE:-authoritative}
      --enable_ops_metrics  true
  dhcp:
    image: nsone/standalone_dhcp:${TAG:-2.1.0}
    environment:        # keep environment lines if 2+ containers
      CONFIG_PORT: 3305 # are on the host machine
      CONTAINER_NAME: ${DHCP_CONTAINER_NAME:-dhcp}
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: supd health --check
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - type: volume
        source: ns1dhcp
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              ${POP_ID:-mypop}
      --server_id           ${SERVER_ID:-myserver}
      --core_host           ${DIST_OR_CORE_HOSTS:-core}
      --enable_ops_metrics  true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.11.0/24
volumes:
  ns1data:
  ns1core:
  ns1dns:
  ns1dhcp:
