apiVersion: v1
kind: Service
metadata:
  name: dns
  labels:
    run: dns
spec:
  ports:
  - port: 3301
    targetPort: http-config
    protocol: TCP
    name: http-config
  - port: 9091
    targetPort: service
    protocol: TCP
    name: service
  - port: 53
    targetPort: dns-udp
    protocol: UDP
    name: dns-udp
  - port: 53
    targetPort: dns-tcp
    protocol: TCP
    name: dns-tcp
  selector:
    app: dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
  labels:
    app: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - name: dns
        image: nsone/standalone_dns:2.2.3
        env:
        - name: CONTAINER_NAME
          value: "dns"
        - name: CONFIG_PORT
          value: "3301"
        ports:
        - name: http-config
          containerPort: 3000
          protocol: TCP
        - name: service
          containerPort: 9090
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        args:
        - "--pop_id=default_pop"
        - "--server_id=default_server"
        - "--core_host=core"
        - "--operation_mode=authoritative"
        - "--enable_ops_metrics=false"
        livenessProbe:
          exec:
            command:
            - supd
            - health
            - --check
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ns1/data
          name: ns1-data
      volumes:
      - name: ns1-data
        emptyDir: {}
      imagePullSecrets:
      - name: docker-creds
